GET http://localhost:3000/posts
Autherization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTmF2ZWVuIE1vaGl0ZSIsImlhdCI6MTY5NDk2MjU4MiwiZXhwIjoxNjk0OTYyNjEyfQ.qNzSC1OE1uoaeJMdktxRIx7J-4AC_SRUCD-7XWgGXfc

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Naveen Mohite"
}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTmF2ZWVuIE1vaGl0ZSIsImlhdCI6MTY5NDk2MjU4Mn0.6SDZW6UUM94tHRGiaeroMYo3xQR5y5bJroYZgYxD_kI"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTmF2ZWVuIE1vaGl0ZSIsImlhdCI6MTY5NDk2MjU4Mn0.6SDZW6UUM94tHRGiaeroMYo3xQR5y5bJroYZgYxD_kI" 
}